# K8s namespace
namespace: tfm-pre-agat-prog

# Nombre de la imagen a desplegar
image:
  repository: agatalba/tfm-mca-filemanagement-oauth2
  tag: "latest"
  
mysql:
  host: "mysql-service.tfm-pre-svc-agat-prog.svc.cluster.local"
  user: "root"
  
service:
  type: ClusterIP
  port: 8081