# Default values for purchases API.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# K8s namespace
namespace: tfm-pre-agat-prog

image:
  repository: agatalba/tfm-mca-filemanagement-oauth2
  tag: "latest"
  
mysql:
  host: "mysql-service.tfm-pre-svc-agat-prog.svc.cluster.local"
  user: "root"
  
service:
  type: ClusterIP
  port: 8081