name: workflow2

on: 
  push :
    branches:
      - develop

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Commit to develop"
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'
      - run: mvn -Dtest="es.urjc.code.daw.library.unitary.**" test
      - run: mvn -Dtest="es.urjc.code.daw.library.e2e.rest.**" test
      - run: mvn -Dtest="es.urjc.code.daw.library.e2e.selenium.**" test